### ISSUE TITLE
Update the API schema with "downloads" and "downloads.open" as optional permissions

### ISSUE THREAD

**Issue by cosminbadescuSV** [mozilla/addons-linter#1893]
### Describe the problem and steps to reproduce it:
Submit an add-on that has “downloads" and "downloads.open” as optional permissions.

### What happened?
The add-on validation has failed and some errors are displayed.

### What did you expect to happen?
The "downloads" and "downloads.open" to be recognized as optional permissions at submit.

### Anything else we should know?
Reproduced on AMO -dev with FF60 on Win 7 64-bit.
![optionalpermissions](https://user-images.githubusercontent.com/15885467/37208233-3f2d8b2e-23a9-11e8-986b-4cadc2118639.gif)

**Comment by EnTeQuAk** [comment]
This should have been fixed with the Firefox 60 #1898 schema import. It'll land this Thursday on production.

**Comment by cosminbadescuSV** [comment]
This issue is still reproducing, please see the attached video.
![bug1893](https://user-images.githubusercontent.com/15885467/37904163-8795289c-3103-11e8-892c-b280494b7be3.gif)

**Comment by cosminbadescuSV** [comment]
This issue is verified as fixed on Firefox 61.0a1 under Wind 7 64-bit.

Please see the attached video:
![bug1893](https://user-images.githubusercontent.com/15885467/38020496-0e18e608-3283-11e8-80c7-da0e82062fcf.gif)
